version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oso_olubunmi
    ports:
      - '7775:3000'
    volumes:
      - .:/app
      - /app/node_modules